name: Discord Test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Linux Test Info
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Test succeeded.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
