name: Discord Test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  discord_notify:
    runs-on: ubuntu-20.04
    steps:
      - uses: rjstone/discord-webhook-notify@v1
      - name: Linux Test Info
        with:
          severity: info
          details: Test succeeded.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
