name: discord-notify-test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  discord-notify:
    runs-on: ubuntu-20.04
    steps:
      - uses: rjstone/discord-webhook-notify@v1
      - name: Test Success
        if: success()
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
      - name: Test Failure
        if: failure()
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
      - name: Test Cancelled
        if: cancelled()
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
